### ISSUE TITLE
always removes n characters on rewrite (n = length of mirror base)

### ISSUE THREAD

**Issue by bugfinder** [openSUSE/mirrorbrain#2] opened 2017-08-03 15:13 UTC
now if you have a master server that is putting it's tree together with a few links in the tree
it may expand the links but then still remove the n characters:
mirror_base=/dist  (5 chars)
link to /mounts/schnell/foo
results in /s/schnell/foo in the end.
and this is not configurable

**Comment by bugfinder** [comment] 2018-09-20 14:49
proposed patch:
<pre>
# cat mirrorbrain-2.18.1_dont_strip_unless_real_basedir.patch
--- mirrorbrain-2.18.1/mod_mirrorbrain/mod_mirrorbrain.c	2017-08-01 16:46:56.455390000 +0200
+++ mirrorbrain-2.18.1/mod_mirrorbrain/mod_mirrorbrain.c	2018-09-20 16:45:27.835409000 +0200
@@ -1889,7 +1891,10 @@
 
     /* the leading directory needs to be stripped from the file path */
     /* a directory from Apache always ends in '/'; a result from realpath() doesn't */
-    filename = realfile + strlen(mirror_base) + 1;
+    /* but only do this if it really starts with mirror_base, otherwise we end */
+    /* up cutting the start of symlinks */
+    if (strncmp(realfile,mirror_base,strlen(mirror_base)) == 0)
+	filename = realfile + strlen(mirror_base) + 1;
 
     if (rep != YUMLIST) {
         /* keep a filename version without leading path, because metalink clients
</pre>

**Comment by bugfinder** [comment] 2018-09-21 13:31
nope, does not work yet. will need to investigate next week.

**Comment by andrii-suse** [comment] 2020-06-02 07:11
I believe this is duplicated by https://github.com/openSUSE/mirrorbrain/issues/23 ?
I am not sure how the best to handle it - just serve directly if symlinked file is outside mirror_base?

**Comment by darix** [comment] 2020-07-10 12:40
Duplicate of #23

**Closed as completed by darix** 2020-07-10 12:40 UTC
Labels: enhancement, Prio2
